stages:
  - test
  - test_deploy
  - prod_deploy

test:
  stage: test
  image: python:3.7.7-buster
  script:
    - pip install -r requirements.txt && pip install coverage
    - nose2 tests
    - prospector
    - coverage run --omit "tests/*" --source . -m nose2 && coverage report -m
    - bash <(curl -s https://codecov.io/bash)

test_deploy:
  stage: test_deploy
  image: python:3.7.7-buster
  script:
    - rm -rf dist
    - pip install -r requirements.txt
    - pip install twine
    - python setup.py sdist
    - echo $PYPIUN
    - twine upload --verbose -u $PYPIUN -p $PYPIPSWD --repository-url https://test.pypi.org/legacy/ dist/*
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == "development"

prod_deploy:
  stage: prod_deploy
  image: python:3.7.7-buster
  script:
    - rm -rf dist
    - pip install -r requirements.txt
    - pip install twine
    - python setup.py sdist
    - twine upload --verbose -u $PYPIUN_PROD -p $PYPIPSWD_PROD dist/*
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == "master"
